name: GCC Problem Matcher
description: Attaches a problem matcher that looks for errors during gcc builds
author: Ammar Askar
branding:
  icon: check-square
  color: yellow
runs:
  using: 'node16'
  main: 'index.js'